---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
apiVersion: logging.managed.openshift.io/v1alpha1
kind: HyperShiftLogForwarder
metadata:
  name: hypershiftlogforwarder-sample
  namespace: openshift-logging
spec:
  outputs:
    - name: remote-elasticsearch-YXB
      secret:
        name: elasticsearch
      type: elasticsearch
  pipelines:
    - name: enable-default-log-store
      inputRefs: [ application, audit, infrastructure ]
      outputRefs: [ default ]
    - name: forward-to-remote
      inputRefs: [ application ]
      outputRefs: [ remote-elasticsearch ]
