apiVersion: logging.managed.openshift.io/v1alpha1
kind: ClusterLogForwarderTemplate
metadata:
  name: logforwarder-sample
  namespace: openshift-logging-forwarder-operator
spec:
  template: 
    outputs:
      - name: remote-elasticsearch
        secret:
          name: elasticsearch
        type: elasticsearch
    pipelines:
      - name: enable-default-log-store
        inputRefs: [ application, audit, infrastructure ]
        outputRefs: [ default ]
      - name: forward-to-remote
        inputRefs: [ application ]
        outputRefs: [ remote-elasticsearch ]
