//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogForwarderTemplate) DeepCopyInto(out *ClusterLogForwarderTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogForwarderTemplate.
func (in *ClusterLogForwarderTemplate) DeepCopy() *ClusterLogForwarderTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterLogForwarderTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLogForwarderTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogForwarderTemplateList) DeepCopyInto(out *ClusterLogForwarderTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterLogForwarderTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogForwarderTemplateList.
func (in *ClusterLogForwarderTemplateList) DeepCopy() *ClusterLogForwarderTemplateList {
	if in == nil {
		return nil
	}
	out := new(ClusterLogForwarderTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLogForwarderTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogForwarderTemplateSpec) DeepCopyInto(out *ClusterLogForwarderTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogForwarderTemplateSpec.
func (in *ClusterLogForwarderTemplateSpec) DeepCopy() *ClusterLogForwarderTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogForwarderTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperShiftLogForwarder) DeepCopyInto(out *HyperShiftLogForwarder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperShiftLogForwarder.
func (in *HyperShiftLogForwarder) DeepCopy() *HyperShiftLogForwarder {
	if in == nil {
		return nil
	}
	out := new(HyperShiftLogForwarder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperShiftLogForwarder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperShiftLogForwarderList) DeepCopyInto(out *HyperShiftLogForwarderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperShiftLogForwarder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperShiftLogForwarderList.
func (in *HyperShiftLogForwarderList) DeepCopy() *HyperShiftLogForwarderList {
	if in == nil {
		return nil
	}
	out := new(HyperShiftLogForwarderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HyperShiftLogForwarderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperShiftLogForwarderSpec) DeepCopyInto(out *HyperShiftLogForwarderSpec) {
	*out = *in
	in.ClusterLogForwarderSpec.DeepCopyInto(&out.ClusterLogForwarderSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperShiftLogForwarderSpec.
func (in *HyperShiftLogForwarderSpec) DeepCopy() *HyperShiftLogForwarderSpec {
	if in == nil {
		return nil
	}
	out := new(HyperShiftLogForwarderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperShiftLogForwarderStatus) DeepCopyInto(out *HyperShiftLogForwarderStatus) {
	*out = *in
	in.ClusterLogForwarderStatus.DeepCopyInto(&out.ClusterLogForwarderStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HyperShiftLogForwarderStatus.
func (in *HyperShiftLogForwarderStatus) DeepCopy() *HyperShiftLogForwarderStatus {
	if in == nil {
		return nil
	}
	out := new(HyperShiftLogForwarderStatus)
	in.DeepCopyInto(out)
	return out
}
